# Generated by Django 6.0.6 on 2026-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario ($)')),
            ],
            options={
                'verbose_name': 'Detalle de la Orden',
                'verbose_name_plural': 'Detalles de las Órdenes',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Orden ($)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('completada', 'Pagado y Entregado'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado de la Orden')),
                ('referencia', models.CharField(max_length=50, verbose_name='Número de Referencia')),
                ('banco_origen', models.CharField(max_length=50, verbose_name='Banco de Origen')),
                ('captura_pago', models.ImageField(upload_to='capturas_tienda/', verbose_name='Captura de Pantalla (Comprobante)')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la Orden')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Inventario / Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
