# Generated by Django 6.0.6 on 2026-07-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Plan')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)')),
                ('duracion_dias', models.PositiveIntegerField(default=30, help_text='Ejemplo: 30 para un mes estándar.', verbose_name='Duración en Días')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('activa', 'Solvente (Activa)'), ('vencida', 'Moroso (Vencida)')], default='pendiente', max_length=15, verbose_name='Estado de Suscripción')),
                ('referencia', models.CharField(max_length=50, verbose_name='Número de Referencia')),
                ('banco_origen', models.CharField(help_text='Banco desde donde el cliente realizó el pago.', max_length=50, verbose_name='Banco de Origen')),
                ('captura_pago', models.ImageField(upload_to='capturas_planes/', verbose_name='Captura de Pantalla (Comprobante)')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memberships.plan', verbose_name='Plan Contratado')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
